### ISSUE TITLE
USER STORY: List of products

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#1]
EPIC: View Products

As a **Shopper** I am able to **view a list of products** so that I can **select some to purchase.**

**Acceptance Criteria**
- Shopper can see a list of all products

**Tasks**
- [x] Create a Django project
- [x] Create Products app
- [x] Upload images
- [x] Add product model
- [x] Write views
- [x] Create template to see all products
