### ISSUE TITLE
USER STORY: User profile

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#10]
EPIC: Registration and Profile

As a **Site User** I am able to **have a personalized user profile** so that I can **view my personal order history and order confirmations, and save my payment information.**

**Acceptance Criteria**
- Site User can login and view their profile with personal information and order history

**Tasks**
- [x] Create Profile app
- [x] Import user model and create user profile model
- [x] Migrate changes
- [x] Create profile template
- [x] Write profile views to render personal information and order history
- [x] Build user profile form
