### ISSUE TITLE
USER STORY: Search for a product

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#13]
EPIC: Sort and Search

As a **Shopper** I am able to **search for a product by name or description** so that I can **find a specific product I'd like to purchase.**

**Acceptance Criteria**
- Shopper can type a name of a product in a search form
- Shopper can see results of their search

**Tasks**
- [x] Add a search form to base template
- [x] Add queries to products view
- [x] Save and test
