### ISSUE TITLE
USER STORY: View bag

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#15]
EPIC: Purchase and Checkout

As a **Shopper** I am able to **view items in my bag to be purchased** so that I can **identify the total cost of my purchase and all items I will receive.**

**Acceptance Criteria**
- Shoppers can tap the bag icon to view the bag page
- The bag page shows list of products, their prices, total and delivery costs

**Tasks**
- [x] Create bag app
- [x] Write views
- [x] Create bag html template
- [x] Add urls to base template to view bag 
- [x] Create contexts.py file to manage a specific user's bag
