### ISSUE TITLE
USER STORY: Adjust quantity of items in bag

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#16]
EPIC: Purchase and Checkout

As a **Shopper** I am able to **adjust the quantity of individual items in my bag** so that I can **easily make changes to my purchase before checkout.**

**Acceptance Criteria**
- Shopper can easily update the quantity of an item in the shopping bag

**Tasks**
- [x] Add the quantity selector box to the shopping bag page's quantity column
- [x] Add form to bag html 
- [x] Write JS to handle the form
- [x] Add view to adjust bag
