### ISSUE TITLE
USER STORY: Enter payment details

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#17]
EPIC: Purchase and Checkout

As a **Shopper** I am able to **easily enter my payment information** so that I can **check out quickly and with no hassles.**

**Acceptance Criteria**
- Shopper can proceed to checkout and see a form for payment details
- Shopper can fill in the form with the required information and submit it

**Tasks**
- [x] Create checkout app
- [x] Add models and signals for an order
- [x] Create a checkout form
- [x] Create a checkout view, url and a template for it
- [x] Install django crispy forms
- [x] After creating user profile, set up the checkout page to autofill the payment form with the user's default delivery information.
