### ISSUE TITLE
USER STORY: Secure payment details

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#18]
EPIC: Purchase and Checkout

As a **Shopper** I am able to **feel my personal and payment information is safe and secure** so that I can **confidently provide the needed information to make a purchase.**

**Acceptance Criteria**
- Payments are implemented by Stripe

**Tasks**
- [x] Register Stripe account
- [x] Add JavaScript code from Stripe to base template
- [x] Write views
- [x] Write JS for stripe elements
- [x] Add CSS from Stripe 
- [x] Add validation
- [x] Test
