### ISSUE TITLE
USER STORY: Email confirmation

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#20]
EPIC: Purchase and Checkout

As a **Shopper** I am able to **receive an email confirmation after checking out** so that I can **keep the confirmation of what I've purchased for my records.**

**Acceptance Criteria**
- After successful checkout, Shoppers get an email confirmation

**Tasks**
- [x] Add webhooks to handle payment
- [x] Create a text file with a confirmation email text
- [x] Write a new method to send emails
- [x] Import django.core.mail
- [x] Test
