### ISSUE TITLE
USER STORY: Add products

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#21]
EPIC: Management

As a **Store Owner** I am able to **add a product** so that I can **add new items to my store.**

**Acceptance Criteria**
- Store Owner when logged in, can easily locate add product button in navbar
- Store Owner can fill out a form to add a product
- The form works properly
- After filling out the form, the product is in the list of all products

**Tasks**
- [x] Create product form in Products app
- [x] Write a view to add products
- [x] Create template for a form
- [x] Add validation to the form
