### ISSUE TITLE
USER STORY: Update products

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#22]
EPIC: Management

As a **Store Owner** I am able to **edit or update a product** so that I can **change product prices, descriptions, images, and other product criteria.**

**Acceptance Criteria**
- Store Owner can click edit/update button
- Store Owner is redirected to a product form
- Store Owner can update the details and save

**Tasks**
- [x] Create edit product template
- [x] Write a new view to edit products
- [x] Connect urls including product id
- [x] Add a success message
- [x] Test editing a product
