### ISSUE TITLE
USER STORY: Delete products

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#23]
EPIC: Management

As a **Store Owner** I am able to **delete a product** so that I can **remove items that are no longer for sale.**

**Acceptance Criteria**
- Store Owner can easily locate Delete product button
- When Delete button is clicked, a product is deleted
- Only Store Owner has access to product management functions

**Tasks**
- [x] Write a view to delete products
- [x] Add url to delete a product with id
- [x] Test by adding a new product and then deleting it
- [x] Add restrictions for superuser security
- [x] Import auth decorators and wrap functions
