### ISSUE TITLE
USER STORY: Subscribe for a newsletter

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#27]
EPIC: Newsletter

As a **Site User** I am able to **subscribe to receive a newsletter** so that I can **keep up to date with new deals and special offers.**

**Acceptance Criteria**
- Site user can see a Subscription button at the bottom of the Homepage.
- Site user can click Subscribe button to open a subscription form.
- Site user can fill out the form.
- Site user can see a success message.

**Tasks**
- [x] Add Subscribe model
- [x] Create a form for subscription
- [x] Write views to render the form
- [x] Connect urls
- [x] Add form validation
