### ISSUE TITLE
USER STORY: Special offers

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#3]
EPIC: View Products

As a **Shopper** I am able to **quickly identify deals and special offers** so that I can **take advantage of special savings on products I'd like to purchase.**

**Acceptance Criteria**
- Shopper can navigate to Deals and Special offers categories in a menu
- Special offers category shows corresponding products

**Tasks**
- [x] Write view to sort products by categories
- [x] Add url to navigation
- [x] Check by clicking every category in menu
- [x] Each category displays corresponding products
