### ISSUE TITLE
USER STORY: Wish list

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#5]
EPIC: Wishlist

As a **Shopper** I am able to **save a desired product to my wish list** so that I can **find it easily to purchase it next time.**

**Acceptance Criteria**
- Product details page contains "Add to wishlist" button
- A Shopper can click the button to add the product to the list

**Tasks**
- [x] Create Wishlist model in checkout app
- [x] Write views
- [x] Add Wishlist html template
- [x] Add "Add to wishlist" button to product_detail template
- [x] Add urls
