### ISSUE TITLE
USER STORY: Email confirmation

### ISSUE THREAD

**Issue by konstanciaa** [konstanciaa/cozy-home#9]
EPIC: Registration and Profile

As a **Site User** I am able to **receive an email confirmation after registering** so that I can **verify that my account registration was successful.**

**Acceptance Criteria**
- Site User receives a confirmation email after registering a new account

**Tasks**
- [x] In your gmail account go to settings
- [x] Create an app password for this django app
- [x] Add generated password to config var in Heroku
- [x] Add email variables to settings file
- [x] Test by registering a new account
